### ISSUE TITLE
Generate pretty diffs error

### ISSUE THREAD

**Issue by puffin** [mathieudutour/git-sketch-plugin#116] opened 2017-05-04 11:53 UTC
### How did it happen?
1. Try to generate pretty diffs and bad things happens..
2.
3.

### Error log

```
mv: rename .exportedArtboards/Reach MVP to .oldArtboards: No such file or directory
/Users/admin/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin//exportArtboard.sh: line 36: ${readmeFile}: ambiguous redirect

```

**Comment by mathieudutour** [comment] 2017-05-05 07:59
I'm going to close this, it's probably a duplicate of #115.

Could you try with v0.11.0?

**Closed as completed by mathieudutour** 2017-05-05 07:59 UTC
