### ISSUE TITLE
Autofocus Cursors in Commit Window.

### ISSUE THREAD

**Issue by saschalichtenstein** [mathieudutour/git-sketch-plugin#89] opened 2017-02-02 09:25 UTC
### How did it happen?
1. Want to commit and not clicking inside the text field.

### Error log

```
{}
```

**Comment by mathieudutour** [comment] 2017-02-02 10:43
Good idea, will see what I can do

**Comment by 0xcaff** [comment] 2017-12-26 21:08
Duplicate of #137

**Closed as completed by 0xcaff** 2017-12-26 21:08 UTC
Labels: feature
