### ISSUE TITLE
error when generate diff files. sketch 46

### ISSUE THREAD

**Issue by tobyforever** [mathieudutour/git-sketch-plugin#162] opened 2017-12-02 13:27 UTC
### How did it happen?
1. error when generate diff files. sketch 46
2.
3.

### Error log

```
Traceback (most recent call last):
  File "/Users/lmz/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/getArtboardNames.py", line 15, in <module>
    name = pageName + "/" + artboardName
TypeError: can't concat bytes to str

```

**Comment by 0xcaff** [comment] 2017-12-26 01:56
Duplicate of #141

**Closed as completed** 2017-12-26 08:57 UTC
