### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by YvetteSystemweb** [mathieudutour/git-sketch-plugin#182] opened 2018-07-04 07:25 UTC
### How did it happen?
1.
2.
3.

### Error log

```
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>


```

**Comment by 0xcaff** [comment] 2018-07-04 15:52
Duplicate of #152

**Closed as completed by 0xcaff** 2018-07-04 15:52 UTC
Labels: question
