### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vonsio** [mathieudutour/git-sketch-plugin#132] opened 2017-05-20 12:11 UTC
### How did it happen?
1. I did the getting started tutorial to add my sketch file to git.
2. I selected the dev branche, made a commit and wanted to push it.

I use an ssh-key but it doesn't work and I'm getting an error like bellow. Other commits to my development repo's are working.

Maybe I'm missing somthing – Thanks for help!
Selim

### Error log

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by eckhardEhm** [comment] 2017-05-23 09:17
bumping this.
from terminal pushing works as im asked for my ssh password.
in my .ssh/config the identity file is set for my the git server domain name.
in keychain sketch.app is added to the identityfile.

**Comment by eckhardEhm** [comment] 2017-05-23 09:24
actually this solved my problem:

https://superuser.com/questions/1127067/macos-keeps-asking-my-ssh-passphrase-since-i-updated-to-sierra

I noticed that terminal kept on asking for my ssh password which didnt happen before i (had to) update to sierra. Solution is the `UseKeychain yes` Option in your
~/.ssh/config file for the git server.

**Comment by 0xcaff** [comment] 2017-12-26 21:20
Duplicate of #95

**Closed as completed by 0xcaff** 2017-12-26 21:20 UTC
Labels: question
