### ISSUE TITLE
can't concat bytes to str

### ISSUE THREAD

**Issue by xujipm** [mathieudutour/git-sketch-plugin#141] opened 2017-06-29 06:40 UTC
### How did it happen?
1.
2.
3.

### Error log

```
Traceback (most recent call last):
  File "/Users/xuji/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Git.sketchplugin/getArtboardNames.py", line 15, in <module>
    name = pageName + "/" + artboardName
TypeError: can't concat bytes to str

```

**Comment by mklarmann** [comment] 2017-10-13 11:11
I have the same issue

**Comment by YoshikiIkegaya** [comment] 2017-11-13 07:57
Same issue happened for me

**Comment by tobyforever** [comment] 2017-12-02 13:28
me too

**Comment by 0xcaff** [comment] 2017-12-26 21:09
Duplicate of #129

**Closed as completed by 0xcaff** 2017-12-26 21:09 UTC
Labels: bug
