### ISSUE TITLE
Error on commit attempt. Possible failure to enter password?

### ISSUE THREAD

**Issue by rebdev** [mathieudutour/git-sketch-plugin#98] opened 2017-03-13 02:33 UTC
### How did it happen?
1. Went Plugins -> Git -> Commit
2. Added a comment.
3. Ticked the 'pretty diffs' box
4. Got 'Failed.... Unknow error' error.

I've added the repo (this I can say for certain because on trying to add it a second time it informed me so) but I haven't entered a password anywhere. Maybe that's causing the problem? Where do enter my password?

### Error log

```
{}
```

**Comment by 0xcaff** [comment] 2017-12-26 21:19
Duplicate of #95

**Closed as completed by 0xcaff** 2017-12-26 21:19 UTC
Labels: question
