### ISSUE TITLE
repository is over 2 GB 

### ISSUE THREAD

**Issue by szapau** [mathieudutour/git-sketch-plugin#146] opened 2017-07-28 15:23 UTC
### How did it happen?
1.
2.
3.

### Error log

```
remote: repository is in read only mode (over 2 GB size limit).        
remote: 
remote: Learn how to reduce your repository size: https://confluence.atlassian.com/x/xgMvEw.        
To https://bitbucket.org/advertima/manager-designs.git
 ! [remote rejected] design -> design (pre-receive hook declined)
error: failed to push some refs to 'https://szatapa@bitbucket.org/advertima/manager-designs.git'

```

**Comment by 0xcaff** [comment] 2017-12-26 01:52
This is caused by the large amount of pngs committed to the repo. You can avoid it by using https://kactus.io . Kactus exports JSON representations of your sketch files and uses a client side desktop tool to diff the representations.

**Comment by mathieudutour** [comment] 2017-12-26 08:59
@0xcaff, seems like you are a bit active on this repo, I can make you a contributor if you want to clean up the repo

**Comment by 0xcaff** [comment] 2017-12-26 17:25
I’d love to be a contributor!

**Comment by 0xcaff** [comment] 2017-12-26 20:56
You could also use [git-lfs](https://github.com/mathieudutour/git-sketch-plugin/blob/2da9827de3a9510eb86fea0e3f0bcb0c14e1380f/docs/git-lfs.md) to avoid this problem.

**Closed as completed** 2017-12-26 21:12 UTC
Labels: question
