### ISSUE TITLE
Exporting artboards issue after updating to 0.9.2

### ISSUE THREAD

**Issue by timohofmeijer** [mathieudutour/git-sketch-plugin#107] opened 2017-04-10 20:25 UTC
After updating to 0.9.2, exporting artboards didn’t work for me anymore. Seems like the new export format is undefined after the update. **Manually setting it to `png` in the preferences, resolved the issue**. If this indeed did cause the issue, a default value could save people a hassle : )

**Comment by mathieudutour** [comment] 2017-04-10 21:01
is it the same error as #106 ? I can't reproduce. But I'll probably add a default if that fix the issue

**Comment by timohofmeijer** [comment] 2017-04-11 05:46
I didn’t get an error, just an empty `.exportedArtboards` directory after running the export command (on multiple existing projects), so I don’t think it’s the same issue.

Offtopic: Looking forward to your proposed solution of creating an image diffing app combined with mergeable sketch files in git! Many thanks for your efforts 👍 😀

**Comment by mathieudutour** [comment] 2017-04-11 09:54
I just published 0.10.0, it should be fixed

**Closed as completed by mathieudutour** 2017-04-11 09:54 UTC
